package ninchatapi

// THIS FILE IS AUTO-GENERATED BY generate.py - DO NOT EDIT BY HAND!

import (
	"github.com/ninchat/ninchat-go"
)

// AccessCreated event.  https://ninchat.com/api/v2#access_created
type AccessCreated struct {
	AccessKey  *string `json:"access_key,omitempty"`
	AccessType string  `json:"access_type"`
}

// String returns "access_created".
func (*AccessCreated) String() string {
	return "access_created"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "access_created".
func (target *AccessCreated) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "access_created" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["access_key"]; x != nil {
		if y, ok := x.(string); ok {
			target.AccessKey = &y
		}
	}

	if x := source["access_type"]; x != nil {
		if y, ok := x.(string); ok {
			target.AccessType = y
		}
	}

	return nil
}

// AccessFound event.  https://ninchat.com/api/v2#access_found
type AccessFound struct {
	AccessType   string        `json:"access_type"`
	ChannelAttrs *ChannelAttrs `json:"channel_attrs,omitempty"`
	ChannelId    *string       `json:"channel_id,omitempty"`
	IdentityName *string       `json:"identity_name,omitempty"`
	IdentityType *string       `json:"identity_type,omitempty"`
	RealmAttrs   *RealmAttrs   `json:"realm_attrs,omitempty"`
	RealmId      *string       `json:"realm_id,omitempty"`
	RealmMember  bool          `json:"realm_member,omitempty"`
	UserAttrs    *UserAttrs    `json:"user_attrs,omitempty"`
	UserId       *string       `json:"user_id,omitempty"`
}

// String returns "access_found".
func (*AccessFound) String() string {
	return "access_found"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "access_found".
func (target *AccessFound) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "access_found" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["access_type"]; x != nil {
		if y, ok := x.(string); ok {
			target.AccessType = y
		}
	}

	if x := source["channel_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.ChannelAttrs = new(ChannelAttrs)
			target.ChannelAttrs.MergeFrom(y)
		}
	}

	if x := source["channel_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.ChannelId = &y
		}
	}

	if x := source["identity_name"]; x != nil {
		if y, ok := x.(string); ok {
			target.IdentityName = &y
		}
	}

	if x := source["identity_type"]; x != nil {
		if y, ok := x.(string); ok {
			target.IdentityType = &y
		}
	}

	if x := source["realm_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.RealmAttrs = new(RealmAttrs)
			target.RealmAttrs.MergeFrom(y)
		}
	}

	if x := source["realm_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.RealmId = &y
		}
	}

	if x := source["realm_member"]; x != nil {
		target.RealmMember = true
	}

	if x := source["user_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.UserAttrs = new(UserAttrs)
			target.UserAttrs.MergeFrom(y)
		}
	}

	if x := source["user_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.UserId = &y
		}
	}

	return nil
}

// AudienceEnqueued event.  https://ninchat.com/api/v2#audience_enqueued
type AudienceEnqueued struct {
	QueueAttrs    *QueueAttrs `json:"queue_attrs"`
	QueueId       string      `json:"queue_id"`
	QueuePosition int         `json:"queue_position"`
}

// String returns "audience_enqueued".
func (*AudienceEnqueued) String() string {
	return "audience_enqueued"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "audience_enqueued".
func (target *AudienceEnqueued) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "audience_enqueued" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["queue_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.QueueAttrs = new(QueueAttrs)
			target.QueueAttrs.MergeFrom(y)
		}
	}

	if x := source["queue_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.QueueId = y
		}
	}

	if x := source["queue_position"]; x != nil {
		if y, ok := x.(int); ok {
			target.QueuePosition = y
		}
	}

	return nil
}

// ChannelDeleted event.  https://ninchat.com/api/v2#channel_deleted
type ChannelDeleted struct {
	ChannelId string `json:"channel_id"`
}

// String returns "channel_deleted".
func (*ChannelDeleted) String() string {
	return "channel_deleted"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "channel_deleted".
func (target *ChannelDeleted) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "channel_deleted" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["channel_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.ChannelId = y
		}
	}

	return nil
}

// ChannelFound event.  https://ninchat.com/api/v2#channel_found
type ChannelFound struct {
	ChannelAttrs   *ChannelAttrs   `json:"channel_attrs"`
	ChannelId      string          `json:"channel_id"`
	ChannelMembers *ChannelMembers `json:"channel_members,omitempty"`
	ChannelStatus  *string         `json:"channel_status,omitempty"`
	RealmId        *string         `json:"realm_id,omitempty"`
}

// String returns "channel_found".
func (*ChannelFound) String() string {
	return "channel_found"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "channel_found".
func (target *ChannelFound) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "channel_found" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["channel_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.ChannelAttrs = new(ChannelAttrs)
			target.ChannelAttrs.MergeFrom(y)
		}
	}

	if x := source["channel_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.ChannelId = y
		}
	}

	if x := source["channel_members"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.ChannelMembers = new(ChannelMembers)
			target.ChannelMembers.MergeFrom(y)
		}
	}

	if x := source["channel_status"]; x != nil {
		if y, ok := x.(string); ok {
			target.ChannelStatus = &y
		}
	}

	if x := source["realm_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.RealmId = &y
		}
	}

	return nil
}

// ChannelJoined event.  https://ninchat.com/api/v2#channel_joined
type ChannelJoined struct {
	ChannelAttrs   *ChannelAttrs   `json:"channel_attrs"`
	ChannelId      string          `json:"channel_id"`
	ChannelMembers *ChannelMembers `json:"channel_members"`
	RealmId        *string         `json:"realm_id,omitempty"`
}

// String returns "channel_joined".
func (*ChannelJoined) String() string {
	return "channel_joined"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "channel_joined".
func (target *ChannelJoined) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "channel_joined" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["channel_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.ChannelAttrs = new(ChannelAttrs)
			target.ChannelAttrs.MergeFrom(y)
		}
	}

	if x := source["channel_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.ChannelId = y
		}
	}

	if x := source["channel_members"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.ChannelMembers = new(ChannelMembers)
			target.ChannelMembers.MergeFrom(y)
		}
	}

	if x := source["realm_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.RealmId = &y
		}
	}

	return nil
}

// ChannelMemberJoined event.  https://ninchat.com/api/v2#channel_member_joined
type ChannelMemberJoined struct {
	ChannelId   string      `json:"channel_id"`
	MemberAttrs interface{} `json:"member_attrs"`
	UserAttrs   *UserAttrs  `json:"user_attrs"`
	UserId      string      `json:"user_id"`
}

// String returns "channel_member_joined".
func (*ChannelMemberJoined) String() string {
	return "channel_member_joined"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "channel_member_joined".
func (target *ChannelMemberJoined) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "channel_member_joined" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["channel_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.ChannelId = y
		}
	}

	if x := source["member_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.MemberAttrs = y
		}
	}

	if x := source["user_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.UserAttrs = new(UserAttrs)
			target.UserAttrs.MergeFrom(y)
		}
	}

	if x := source["user_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.UserId = y
		}
	}

	return nil
}

// ChannelMemberParted event.  https://ninchat.com/api/v2#channel_member_parted
type ChannelMemberParted struct {
	ChannelId *string `json:"channel_id,omitempty"`
	RealmId   *string `json:"realm_id,omitempty"`
	UserId    string  `json:"user_id"`
}

// String returns "channel_member_parted".
func (*ChannelMemberParted) String() string {
	return "channel_member_parted"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "channel_member_parted".
func (target *ChannelMemberParted) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "channel_member_parted" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["channel_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.ChannelId = &y
		}
	}

	if x := source["realm_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.RealmId = &y
		}
	}

	if x := source["user_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.UserId = y
		}
	}

	return nil
}

// ChannelMemberUpdated event.  https://ninchat.com/api/v2#channel_member_updated
type ChannelMemberUpdated struct {
	ChannelId   *string     `json:"channel_id,omitempty"`
	MemberAttrs interface{} `json:"member_attrs"`
	RealmId     *string     `json:"realm_id,omitempty"`
	UserId      string      `json:"user_id"`
}

// String returns "channel_member_updated".
func (*ChannelMemberUpdated) String() string {
	return "channel_member_updated"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "channel_member_updated".
func (target *ChannelMemberUpdated) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "channel_member_updated" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["channel_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.ChannelId = &y
		}
	}

	if x := source["member_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.MemberAttrs = y
		}
	}

	if x := source["realm_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.RealmId = &y
		}
	}

	if x := source["user_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.UserId = y
		}
	}

	return nil
}

// ChannelParted event.  https://ninchat.com/api/v2#channel_parted
type ChannelParted struct {
	ChannelId string `json:"channel_id"`
}

// String returns "channel_parted".
func (*ChannelParted) String() string {
	return "channel_parted"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "channel_parted".
func (target *ChannelParted) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "channel_parted" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["channel_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.ChannelId = y
		}
	}

	return nil
}

// ChannelUpdated event.  https://ninchat.com/api/v2#channel_updated
type ChannelUpdated struct {
	ChannelAttrs *ChannelAttrs `json:"channel_attrs"`
	ChannelId    string        `json:"channel_id"`
	RealmId      *string       `json:"realm_id,omitempty"`
}

// String returns "channel_updated".
func (*ChannelUpdated) String() string {
	return "channel_updated"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "channel_updated".
func (target *ChannelUpdated) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "channel_updated" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["channel_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.ChannelAttrs = new(ChannelAttrs)
			target.ChannelAttrs.MergeFrom(y)
		}
	}

	if x := source["channel_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.ChannelId = y
		}
	}

	if x := source["realm_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.RealmId = &y
		}
	}

	return nil
}

// DialogueUpdated event.  https://ninchat.com/api/v2#dialogue_updated
type DialogueUpdated struct {
	AudienceMetadata map[string]interface{} `json:"audience_metadata,omitempty"`
	DialogueMembers  *DialogueMembers       `json:"dialogue_members"`
	DialogueStatus   *string                `json:"dialogue_status,omitempty"`
	UserId           string                 `json:"user_id"`
}

// String returns "dialogue_updated".
func (*DialogueUpdated) String() string {
	return "dialogue_updated"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "dialogue_updated".
func (target *DialogueUpdated) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "dialogue_updated" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["audience_metadata"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.AudienceMetadata = y
		}
	}

	if x := source["dialogue_members"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.DialogueMembers = new(DialogueMembers)
			target.DialogueMembers.MergeFrom(y)
		}
	}

	if x := source["dialogue_status"]; x != nil {
		if y, ok := x.(string); ok {
			target.DialogueStatus = &y
		}
	}

	if x := source["user_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.UserId = y
		}
	}

	return nil
}

// Error event.  https://ninchat.com/api/v2#error
type Error struct {
	ChannelId    *string `json:"channel_id,omitempty"`
	ErrorReason  *string `json:"error_reason,omitempty"`
	ErrorType    string  `json:"error_type"`
	IdentityName *string `json:"identity_name,omitempty"`
	IdentityType *string `json:"identity_type,omitempty"`
	MessageType  *string `json:"message_type,omitempty"`
	QueueId      *string `json:"queue_id,omitempty"`
	RealmId      *string `json:"realm_id,omitempty"`
	UserId       *string `json:"user_id,omitempty"`
}

// String returns "error".
func (*Error) String() string {
	return "error"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "error".
func (target *Error) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "error" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["channel_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.ChannelId = &y
		}
	}

	if x := source["error_reason"]; x != nil {
		if y, ok := x.(string); ok {
			target.ErrorReason = &y
		}
	}

	if x := source["error_type"]; x != nil {
		if y, ok := x.(string); ok {
			target.ErrorType = y
		}
	}

	if x := source["identity_name"]; x != nil {
		if y, ok := x.(string); ok {
			target.IdentityName = &y
		}
	}

	if x := source["identity_type"]; x != nil {
		if y, ok := x.(string); ok {
			target.IdentityType = &y
		}
	}

	if x := source["message_type"]; x != nil {
		if y, ok := x.(string); ok {
			target.MessageType = &y
		}
	}

	if x := source["queue_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.QueueId = &y
		}
	}

	if x := source["realm_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.RealmId = &y
		}
	}

	if x := source["user_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.UserId = &y
		}
	}

	return nil
}

// HistoryDiscarded event.  https://ninchat.com/api/v2#history_discarded
type HistoryDiscarded struct {
	ChannelId *string `json:"channel_id,omitempty"`
	MessageId string  `json:"message_id"`
	UserId    *string `json:"user_id,omitempty"`
}

// String returns "history_discarded".
func (*HistoryDiscarded) String() string {
	return "history_discarded"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "history_discarded".
func (target *HistoryDiscarded) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "history_discarded" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["channel_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.ChannelId = &y
		}
	}

	if x := source["message_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.MessageId = y
		}
	}

	if x := source["user_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.UserId = &y
		}
	}

	return nil
}

// HistoryResults event.  https://ninchat.com/api/v2#history_results
type HistoryResults struct {
	ChannelId     *string `json:"channel_id,omitempty"`
	HistoryLength int     `json:"history_length"`
	UserId        *string `json:"user_id,omitempty"`
}

// String returns "history_results".
func (*HistoryResults) String() string {
	return "history_results"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "history_results".
func (target *HistoryResults) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "history_results" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["channel_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.ChannelId = &y
		}
	}

	if x := source["history_length"]; x != nil {
		if y, ok := x.(int); ok {
			target.HistoryLength = y
		}
	}

	if x := source["user_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.UserId = &y
		}
	}

	return nil
}

// IdentityCreated event.  https://ninchat.com/api/v2#identity_created
type IdentityCreated struct {
	IdentityAttrs *IdentityAttrs `json:"identity_attrs"`
	IdentityName  string         `json:"identity_name"`
	IdentityType  string         `json:"identity_type"`
}

// String returns "identity_created".
func (*IdentityCreated) String() string {
	return "identity_created"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "identity_created".
func (target *IdentityCreated) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "identity_created" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["identity_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.IdentityAttrs = new(IdentityAttrs)
			target.IdentityAttrs.MergeFrom(y)
		}
	}

	if x := source["identity_name"]; x != nil {
		if y, ok := x.(string); ok {
			target.IdentityName = y
		}
	}

	if x := source["identity_type"]; x != nil {
		if y, ok := x.(string); ok {
			target.IdentityType = y
		}
	}

	return nil
}

// IdentityDeleted event.  https://ninchat.com/api/v2#identity_deleted
type IdentityDeleted struct {
	IdentityName string `json:"identity_name"`
	IdentityType string `json:"identity_type"`
}

// String returns "identity_deleted".
func (*IdentityDeleted) String() string {
	return "identity_deleted"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "identity_deleted".
func (target *IdentityDeleted) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "identity_deleted" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["identity_name"]; x != nil {
		if y, ok := x.(string); ok {
			target.IdentityName = y
		}
	}

	if x := source["identity_type"]; x != nil {
		if y, ok := x.(string); ok {
			target.IdentityType = y
		}
	}

	return nil
}

// IdentityFound event.  https://ninchat.com/api/v2#identity_found
type IdentityFound struct {
	IdentityAttrs *IdentityAttrs `json:"identity_attrs,omitempty"`
	IdentityName  string         `json:"identity_name"`
	IdentityType  string         `json:"identity_type"`
	UserId        string         `json:"user_id"`
}

// String returns "identity_found".
func (*IdentityFound) String() string {
	return "identity_found"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "identity_found".
func (target *IdentityFound) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "identity_found" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["identity_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.IdentityAttrs = new(IdentityAttrs)
			target.IdentityAttrs.MergeFrom(y)
		}
	}

	if x := source["identity_name"]; x != nil {
		if y, ok := x.(string); ok {
			target.IdentityName = y
		}
	}

	if x := source["identity_type"]; x != nil {
		if y, ok := x.(string); ok {
			target.IdentityType = y
		}
	}

	if x := source["user_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.UserId = y
		}
	}

	return nil
}

// IdentityUpdated event.  https://ninchat.com/api/v2#identity_updated
type IdentityUpdated struct {
	IdentityAttrs *IdentityAttrs `json:"identity_attrs"`
	IdentityName  string         `json:"identity_name"`
	IdentityType  string         `json:"identity_type"`
}

// String returns "identity_updated".
func (*IdentityUpdated) String() string {
	return "identity_updated"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "identity_updated".
func (target *IdentityUpdated) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "identity_updated" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["identity_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.IdentityAttrs = new(IdentityAttrs)
			target.IdentityAttrs.MergeFrom(y)
		}
	}

	if x := source["identity_name"]; x != nil {
		if y, ok := x.(string); ok {
			target.IdentityName = y
		}
	}

	if x := source["identity_type"]; x != nil {
		if y, ok := x.(string); ok {
			target.IdentityType = y
		}
	}

	return nil
}

// MasterFound event.  https://ninchat.com/api/v2#master_found
type MasterFound struct {
	MasterKeys *MasterKeys `json:"master_keys"`
}

// String returns "master_found".
func (*MasterFound) String() string {
	return "master_found"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "master_found".
func (target *MasterFound) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "master_found" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["master_keys"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.MasterKeys = new(MasterKeys)
			target.MasterKeys.MergeFrom(y)
		}
	}

	return nil
}

// MasterKeyCreated event.  https://ninchat.com/api/v2#master_key_created
type MasterKeyCreated struct {
	MasterKeyId     string  `json:"master_key_id"`
	MasterKeySecret *string `json:"master_key_secret,omitempty"`
}

// String returns "master_key_created".
func (*MasterKeyCreated) String() string {
	return "master_key_created"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "master_key_created".
func (target *MasterKeyCreated) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "master_key_created" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["master_key_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.MasterKeyId = y
		}
	}

	if x := source["master_key_secret"]; x != nil {
		if y, ok := x.(string); ok {
			target.MasterKeySecret = &y
		}
	}

	return nil
}

// MasterKeyDeleted event.  https://ninchat.com/api/v2#master_key_deleted
type MasterKeyDeleted struct {
	MasterKeyId string `json:"master_key_id"`
}

// String returns "master_key_deleted".
func (*MasterKeyDeleted) String() string {
	return "master_key_deleted"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "master_key_deleted".
func (target *MasterKeyDeleted) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "master_key_deleted" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["master_key_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.MasterKeyId = y
		}
	}

	return nil
}

// MessageReceived event.  https://ninchat.com/api/v2#message_received
type MessageReceived struct {
	ChannelId           *string  `json:"channel_id,omitempty"`
	HistoryLength       *int     `json:"history_length,omitempty"`
	MessageFold         bool     `json:"message_fold,omitempty"`
	MessageHidden       bool     `json:"message_hidden,omitempty"`
	MessageId           string   `json:"message_id"`
	MessageRecipientIds []string `json:"message_recipient_ids,omitempty"`
	MessageTime         float64  `json:"message_time"`
	MessageTtl          *float64 `json:"message_ttl,omitempty"`
	MessageType         string   `json:"message_type"`
	MessageUserId       *string  `json:"message_user_id,omitempty"`
	MessageUserName     *string  `json:"message_user_name,omitempty"`
	UserId              *string  `json:"user_id,omitempty"`
	Payload             [][]byte
}

// String returns "message_received".
func (*MessageReceived) String() string {
	return "message_received"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "message_received".
func (target *MessageReceived) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "message_received" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["channel_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.ChannelId = &y
		}
	}

	if x := source["history_length"]; x != nil {
		if y, ok := x.(int); ok {
			target.HistoryLength = &y
		}
	}

	if x := source["message_fold"]; x != nil {
		target.MessageFold = true
	}

	if x := source["message_hidden"]; x != nil {
		target.MessageHidden = true
	}

	if x := source["message_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.MessageId = y
		}
	}

	if x := source["message_recipient_ids"]; x != nil {
		if y, ok := x.([]string); ok {
			target.MessageRecipientIds = y
		}
	}

	if x := source["message_time"]; x != nil {
		if y, ok := x.(float64); ok {
			target.MessageTime = y
		}
	}

	if x := source["message_ttl"]; x != nil {
		if y, ok := x.(float64); ok {
			target.MessageTtl = &y
		}
	}

	if x := source["message_type"]; x != nil {
		if y, ok := x.(string); ok {
			target.MessageType = y
		}
	}

	if x := source["message_user_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.MessageUserId = &y
		}
	}

	if x := source["message_user_name"]; x != nil {
		if y, ok := x.(string); ok {
			target.MessageUserName = &y
		}
	}

	if x := source["user_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.UserId = &y
		}
	}

	target.Payload = clientEvent.Payload

	return nil
}

// MessageUpdated event.  https://ninchat.com/api/v2#message_updated
type MessageUpdated struct {
	ChannelId     *string `json:"channel_id,omitempty"`
	MessageHidden bool    `json:"message_hidden,omitempty"`
	MessageId     string  `json:"message_id"`
}

// String returns "message_updated".
func (*MessageUpdated) String() string {
	return "message_updated"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "message_updated".
func (target *MessageUpdated) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "message_updated" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["channel_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.ChannelId = &y
		}
	}

	if x := source["message_hidden"]; x != nil {
		target.MessageHidden = true
	}

	if x := source["message_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.MessageId = y
		}
	}

	return nil
}

// Pong event.  https://ninchat.com/api/v2#pong
type Pong struct {
}

// String returns "pong".
func (*Pong) String() string {
	return "pong"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "pong".
func (target *Pong) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "pong" {
		return &UnexpectedEventError{clientEvent}
	}

	return nil
}

// QueueCreated event.  https://ninchat.com/api/v2#queue_created
type QueueCreated struct {
	QueueAttrs *QueueAttrs `json:"queue_attrs"`
	QueueId    string      `json:"queue_id"`
	RealmId    *string     `json:"realm_id,omitempty"`
}

// String returns "queue_created".
func (*QueueCreated) String() string {
	return "queue_created"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "queue_created".
func (target *QueueCreated) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "queue_created" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["queue_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.QueueAttrs = new(QueueAttrs)
			target.QueueAttrs.MergeFrom(y)
		}
	}

	if x := source["queue_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.QueueId = y
		}
	}

	if x := source["realm_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.RealmId = &y
		}
	}

	return nil
}

// QueueDeleted event.  https://ninchat.com/api/v2#queue_deleted
type QueueDeleted struct {
	QueueId string  `json:"queue_id"`
	RealmId *string `json:"realm_id,omitempty"`
}

// String returns "queue_deleted".
func (*QueueDeleted) String() string {
	return "queue_deleted"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "queue_deleted".
func (target *QueueDeleted) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "queue_deleted" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["queue_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.QueueId = y
		}
	}

	if x := source["realm_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.RealmId = &y
		}
	}

	return nil
}

// QueueFound event.  https://ninchat.com/api/v2#queue_found
type QueueFound struct {
	QueueAttrs    *QueueAttrs   `json:"queue_attrs"`
	QueueId       string        `json:"queue_id"`
	QueueMembers  *QueueMembers `json:"queue_members,omitempty"`
	QueuePosition *int          `json:"queue_position,omitempty"`
	RealmId       *string       `json:"realm_id,omitempty"`
}

// String returns "queue_found".
func (*QueueFound) String() string {
	return "queue_found"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "queue_found".
func (target *QueueFound) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "queue_found" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["queue_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.QueueAttrs = new(QueueAttrs)
			target.QueueAttrs.MergeFrom(y)
		}
	}

	if x := source["queue_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.QueueId = y
		}
	}

	if x := source["queue_members"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.QueueMembers = new(QueueMembers)
			target.QueueMembers.MergeFrom(y)
		}
	}

	if x := source["queue_position"]; x != nil {
		if y, ok := x.(int); ok {
			target.QueuePosition = &y
		}
	}

	if x := source["realm_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.RealmId = &y
		}
	}

	return nil
}

// QueueJoined event.  https://ninchat.com/api/v2#queue_joined
type QueueJoined struct {
	QueueAttrs *QueueAttrs `json:"queue_attrs"`
	QueueId    string      `json:"queue_id"`
	RealmId    *string     `json:"realm_id,omitempty"`
}

// String returns "queue_joined".
func (*QueueJoined) String() string {
	return "queue_joined"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "queue_joined".
func (target *QueueJoined) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "queue_joined" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["queue_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.QueueAttrs = new(QueueAttrs)
			target.QueueAttrs.MergeFrom(y)
		}
	}

	if x := source["queue_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.QueueId = y
		}
	}

	if x := source["realm_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.RealmId = &y
		}
	}

	return nil
}

// QueueMemberJoined event.  https://ninchat.com/api/v2#queue_member_joined
type QueueMemberJoined struct {
	MemberAttrs interface{} `json:"member_attrs"`
	QueueId     string      `json:"queue_id"`
	UserAttrs   *UserAttrs  `json:"user_attrs"`
	UserId      string      `json:"user_id"`
}

// String returns "queue_member_joined".
func (*QueueMemberJoined) String() string {
	return "queue_member_joined"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "queue_member_joined".
func (target *QueueMemberJoined) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "queue_member_joined" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["member_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.MemberAttrs = y
		}
	}

	if x := source["queue_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.QueueId = y
		}
	}

	if x := source["user_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.UserAttrs = new(UserAttrs)
			target.UserAttrs.MergeFrom(y)
		}
	}

	if x := source["user_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.UserId = y
		}
	}

	return nil
}

// QueueMemberParted event.  https://ninchat.com/api/v2#queue_member_parted
type QueueMemberParted struct {
	QueueId string `json:"queue_id"`
	UserId  string `json:"user_id"`
}

// String returns "queue_member_parted".
func (*QueueMemberParted) String() string {
	return "queue_member_parted"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "queue_member_parted".
func (target *QueueMemberParted) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "queue_member_parted" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["queue_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.QueueId = y
		}
	}

	if x := source["user_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.UserId = y
		}
	}

	return nil
}

// QueueParted event.  https://ninchat.com/api/v2#queue_parted
type QueueParted struct {
	QueueId string  `json:"queue_id"`
	RealmId *string `json:"realm_id,omitempty"`
}

// String returns "queue_parted".
func (*QueueParted) String() string {
	return "queue_parted"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "queue_parted".
func (target *QueueParted) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "queue_parted" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["queue_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.QueueId = y
		}
	}

	if x := source["realm_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.RealmId = &y
		}
	}

	return nil
}

// QueueUpdated event.  https://ninchat.com/api/v2#queue_updated
type QueueUpdated struct {
	QueueAttrs    *QueueAttrs `json:"queue_attrs"`
	QueueId       string      `json:"queue_id"`
	QueuePosition *int        `json:"queue_position,omitempty"`
	RealmId       *string     `json:"realm_id,omitempty"`
}

// String returns "queue_updated".
func (*QueueUpdated) String() string {
	return "queue_updated"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "queue_updated".
func (target *QueueUpdated) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "queue_updated" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["queue_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.QueueAttrs = new(QueueAttrs)
			target.QueueAttrs.MergeFrom(y)
		}
	}

	if x := source["queue_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.QueueId = y
		}
	}

	if x := source["queue_position"]; x != nil {
		if y, ok := x.(int); ok {
			target.QueuePosition = &y
		}
	}

	if x := source["realm_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.RealmId = &y
		}
	}

	return nil
}

// RealmDeleted event.  https://ninchat.com/api/v2#realm_deleted
type RealmDeleted struct {
	RealmId string `json:"realm_id"`
}

// String returns "realm_deleted".
func (*RealmDeleted) String() string {
	return "realm_deleted"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "realm_deleted".
func (target *RealmDeleted) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "realm_deleted" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["realm_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.RealmId = y
		}
	}

	return nil
}

// RealmFound event.  https://ninchat.com/api/v2#realm_found
type RealmFound struct {
	RealmAttrs   *RealmAttrs   `json:"realm_attrs"`
	RealmId      string        `json:"realm_id"`
	RealmMembers *RealmMembers `json:"realm_members,omitempty"`
}

// String returns "realm_found".
func (*RealmFound) String() string {
	return "realm_found"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "realm_found".
func (target *RealmFound) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "realm_found" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["realm_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.RealmAttrs = new(RealmAttrs)
			target.RealmAttrs.MergeFrom(y)
		}
	}

	if x := source["realm_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.RealmId = y
		}
	}

	if x := source["realm_members"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.RealmMembers = new(RealmMembers)
			target.RealmMembers.MergeFrom(y)
		}
	}

	return nil
}

// RealmJoined event.  https://ninchat.com/api/v2#realm_joined
type RealmJoined struct {
	RealmAttrs   *RealmAttrs   `json:"realm_attrs"`
	RealmId      string        `json:"realm_id"`
	RealmMembers *RealmMembers `json:"realm_members"`
}

// String returns "realm_joined".
func (*RealmJoined) String() string {
	return "realm_joined"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "realm_joined".
func (target *RealmJoined) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "realm_joined" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["realm_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.RealmAttrs = new(RealmAttrs)
			target.RealmAttrs.MergeFrom(y)
		}
	}

	if x := source["realm_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.RealmId = y
		}
	}

	if x := source["realm_members"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.RealmMembers = new(RealmMembers)
			target.RealmMembers.MergeFrom(y)
		}
	}

	return nil
}

// RealmMemberJoined event.  https://ninchat.com/api/v2#realm_member_joined
type RealmMemberJoined struct {
	MemberAttrs interface{} `json:"member_attrs"`
	RealmId     string      `json:"realm_id"`
	UserAttrs   *UserAttrs  `json:"user_attrs"`
	UserId      string      `json:"user_id"`
}

// String returns "realm_member_joined".
func (*RealmMemberJoined) String() string {
	return "realm_member_joined"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "realm_member_joined".
func (target *RealmMemberJoined) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "realm_member_joined" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["member_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.MemberAttrs = y
		}
	}

	if x := source["realm_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.RealmId = y
		}
	}

	if x := source["user_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.UserAttrs = new(UserAttrs)
			target.UserAttrs.MergeFrom(y)
		}
	}

	if x := source["user_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.UserId = y
		}
	}

	return nil
}

// RealmMemberParted event.  https://ninchat.com/api/v2#realm_member_parted
type RealmMemberParted struct {
	ChannelId *string `json:"channel_id,omitempty"`
	RealmId   *string `json:"realm_id,omitempty"`
	UserId    string  `json:"user_id"`
}

// String returns "realm_member_parted".
func (*RealmMemberParted) String() string {
	return "realm_member_parted"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "realm_member_parted".
func (target *RealmMemberParted) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "realm_member_parted" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["channel_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.ChannelId = &y
		}
	}

	if x := source["realm_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.RealmId = &y
		}
	}

	if x := source["user_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.UserId = y
		}
	}

	return nil
}

// RealmMemberUpdated event.  https://ninchat.com/api/v2#realm_member_updated
type RealmMemberUpdated struct {
	MemberAttrs interface{} `json:"member_attrs"`
	RealmId     string      `json:"realm_id"`
	UserId      string      `json:"user_id"`
}

// String returns "realm_member_updated".
func (*RealmMemberUpdated) String() string {
	return "realm_member_updated"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "realm_member_updated".
func (target *RealmMemberUpdated) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "realm_member_updated" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["member_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.MemberAttrs = y
		}
	}

	if x := source["realm_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.RealmId = y
		}
	}

	if x := source["user_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.UserId = y
		}
	}

	return nil
}

// RealmParted event.  https://ninchat.com/api/v2#realm_parted
type RealmParted struct {
	RealmId string `json:"realm_id"`
}

// String returns "realm_parted".
func (*RealmParted) String() string {
	return "realm_parted"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "realm_parted".
func (target *RealmParted) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "realm_parted" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["realm_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.RealmId = y
		}
	}

	return nil
}

// RealmQueuesFound event.  https://ninchat.com/api/v2#realm_queues_found
type RealmQueuesFound struct {
	RealmId     string       `json:"realm_id"`
	RealmQueues *RealmQueues `json:"realm_queues"`
}

// String returns "realm_queues_found".
func (*RealmQueuesFound) String() string {
	return "realm_queues_found"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "realm_queues_found".
func (target *RealmQueuesFound) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "realm_queues_found" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["realm_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.RealmId = y
		}
	}

	if x := source["realm_queues"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.RealmQueues = new(RealmQueues)
			target.RealmQueues.MergeFrom(y)
		}
	}

	return nil
}

// RealmUpdated event.  https://ninchat.com/api/v2#realm_updated
type RealmUpdated struct {
	RealmAttrs *RealmAttrs `json:"realm_attrs"`
	RealmId    string      `json:"realm_id"`
}

// String returns "realm_updated".
func (*RealmUpdated) String() string {
	return "realm_updated"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "realm_updated".
func (target *RealmUpdated) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "realm_updated" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["realm_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.RealmAttrs = new(RealmAttrs)
			target.RealmAttrs.MergeFrom(y)
		}
	}

	if x := source["realm_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.RealmId = y
		}
	}

	return nil
}

// SearchResults event.  https://ninchat.com/api/v2#search_results
type SearchResults struct {
	Channels *Channels `json:"channels,omitempty"`
	Users    *Users    `json:"users,omitempty"`
}

// String returns "search_results".
func (*SearchResults) String() string {
	return "search_results"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "search_results".
func (target *SearchResults) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "search_results" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["channels"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.Channels = new(Channels)
			target.Channels.MergeFrom(y)
		}
	}

	if x := source["users"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.Users = new(Users)
			target.Users.MergeFrom(y)
		}
	}

	return nil
}

// SessionCreated event.  https://ninchat.com/api/v2#session_created
type SessionCreated struct {
	SessionHost      *string                `json:"session_host,omitempty"`
	SessionId        string                 `json:"session_id"`
	UserAccount      *UserAccount           `json:"user_account"`
	UserAttrs        *UserAttrs             `json:"user_attrs"`
	UserAuth         *string                `json:"user_auth,omitempty"`
	UserChannels     *UserChannels          `json:"user_channels"`
	UserDialogues    *UserDialogues         `json:"user_dialogues"`
	UserId           string                 `json:"user_id"`
	UserIdentities   *UserIdentities        `json:"user_identities"`
	UserQueues       *UserQueues            `json:"user_queues,omitempty"`
	UserRealms       *UserRealms            `json:"user_realms"`
	UserRealmsMember *UserRealmsMember      `json:"user_realms_member,omitempty"`
	UserSettings     map[string]interface{} `json:"user_settings"`
}

// String returns "session_created".
func (*SessionCreated) String() string {
	return "session_created"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "session_created".
func (target *SessionCreated) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "session_created" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["session_host"]; x != nil {
		if y, ok := x.(string); ok {
			target.SessionHost = &y
		}
	}

	if x := source["session_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.SessionId = y
		}
	}

	if x := source["user_account"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.UserAccount = new(UserAccount)
			target.UserAccount.MergeFrom(y)
		}
	}

	if x := source["user_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.UserAttrs = new(UserAttrs)
			target.UserAttrs.MergeFrom(y)
		}
	}

	if x := source["user_auth"]; x != nil {
		if y, ok := x.(string); ok {
			target.UserAuth = &y
		}
	}

	if x := source["user_channels"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.UserChannels = new(UserChannels)
			target.UserChannels.MergeFrom(y)
		}
	}

	if x := source["user_dialogues"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.UserDialogues = new(UserDialogues)
			target.UserDialogues.MergeFrom(y)
		}
	}

	if x := source["user_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.UserId = y
		}
	}

	if x := source["user_identities"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.UserIdentities = new(UserIdentities)
			target.UserIdentities.MergeFrom(y)
		}
	}

	if x := source["user_queues"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.UserQueues = new(UserQueues)
			target.UserQueues.MergeFrom(y)
		}
	}

	if x := source["user_realms"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.UserRealms = new(UserRealms)
			target.UserRealms.MergeFrom(y)
		}
	}

	if x := source["user_realms_member"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.UserRealmsMember = new(UserRealmsMember)
			target.UserRealmsMember.MergeFrom(y)
		}
	}

	if x := source["user_settings"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.UserSettings = y
		}
	}

	return nil
}

// SessionStatusUpdated event.  https://ninchat.com/api/v2#session_status_updated
type SessionStatusUpdated struct {
	ChannelId *string `json:"channel_id,omitempty"`
	MessageId string  `json:"message_id"`
	UserId    *string `json:"user_id,omitempty"`
}

// String returns "session_status_updated".
func (*SessionStatusUpdated) String() string {
	return "session_status_updated"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "session_status_updated".
func (target *SessionStatusUpdated) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "session_status_updated" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["channel_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.ChannelId = &y
		}
	}

	if x := source["message_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.MessageId = y
		}
	}

	if x := source["user_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.UserId = &y
		}
	}

	return nil
}

// UserDeleted event.  https://ninchat.com/api/v2#user_deleted
type UserDeleted struct {
	UserId string `json:"user_id"`
}

// String returns "user_deleted".
func (*UserDeleted) String() string {
	return "user_deleted"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "user_deleted".
func (target *UserDeleted) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "user_deleted" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["user_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.UserId = y
		}
	}

	return nil
}

// UserFound event.  https://ninchat.com/api/v2#user_found
type UserFound struct {
	AudienceMetadata map[string]interface{} `json:"audience_metadata,omitempty"`
	DialogueMembers  *DialogueMembers       `json:"dialogue_members,omitempty"`
	DialogueStatus   *string                `json:"dialogue_status,omitempty"`
	UserAccount      *UserAccount           `json:"user_account,omitempty"`
	UserAttrs        *UserAttrs             `json:"user_attrs"`
	UserChannels     *UserChannels          `json:"user_channels,omitempty"`
	UserDialogues    *UserDialogues         `json:"user_dialogues,omitempty"`
	UserId           string                 `json:"user_id"`
	UserIdentities   *UserIdentities        `json:"user_identities"`
	UserQueues       *UserQueues            `json:"user_queues,omitempty"`
	UserRealms       *UserRealms            `json:"user_realms,omitempty"`
	UserRealmsMember *UserRealmsMember      `json:"user_realms_member,omitempty"`
	UserSettings     map[string]interface{} `json:"user_settings,omitempty"`
}

// String returns "user_found".
func (*UserFound) String() string {
	return "user_found"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "user_found".
func (target *UserFound) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "user_found" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["audience_metadata"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.AudienceMetadata = y
		}
	}

	if x := source["dialogue_members"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.DialogueMembers = new(DialogueMembers)
			target.DialogueMembers.MergeFrom(y)
		}
	}

	if x := source["dialogue_status"]; x != nil {
		if y, ok := x.(string); ok {
			target.DialogueStatus = &y
		}
	}

	if x := source["user_account"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.UserAccount = new(UserAccount)
			target.UserAccount.MergeFrom(y)
		}
	}

	if x := source["user_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.UserAttrs = new(UserAttrs)
			target.UserAttrs.MergeFrom(y)
		}
	}

	if x := source["user_channels"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.UserChannels = new(UserChannels)
			target.UserChannels.MergeFrom(y)
		}
	}

	if x := source["user_dialogues"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.UserDialogues = new(UserDialogues)
			target.UserDialogues.MergeFrom(y)
		}
	}

	if x := source["user_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.UserId = y
		}
	}

	if x := source["user_identities"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.UserIdentities = new(UserIdentities)
			target.UserIdentities.MergeFrom(y)
		}
	}

	if x := source["user_queues"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.UserQueues = new(UserQueues)
			target.UserQueues.MergeFrom(y)
		}
	}

	if x := source["user_realms"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.UserRealms = new(UserRealms)
			target.UserRealms.MergeFrom(y)
		}
	}

	if x := source["user_realms_member"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.UserRealmsMember = new(UserRealmsMember)
			target.UserRealmsMember.MergeFrom(y)
		}
	}

	if x := source["user_settings"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.UserSettings = y
		}
	}

	return nil
}

// UserUpdated event.  https://ninchat.com/api/v2#user_updated
type UserUpdated struct {
	UserAccount  *UserAccount           `json:"user_account,omitempty"`
	UserAttrs    *UserAttrs             `json:"user_attrs"`
	UserId       string                 `json:"user_id"`
	UserSettings map[string]interface{} `json:"user_settings,omitempty"`
}

// String returns "user_updated".
func (*UserUpdated) String() string {
	return "user_updated"
}

// MergeFrom fills in the parameters specified by the clientEvent.  An
// UnexpectedEventError is returned if its type is not "user_updated".
func (target *UserUpdated) MergeFrom(clientEvent *ninchat.Event) error {
	if clientEvent.String() != "user_updated" {
		return &UnexpectedEventError{clientEvent}
	}

	source := clientEvent.Params

	if x := source["user_account"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.UserAccount = new(UserAccount)
			target.UserAccount.MergeFrom(y)
		}
	}

	if x := source["user_attrs"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.UserAttrs = new(UserAttrs)
			target.UserAttrs.MergeFrom(y)
		}
	}

	if x := source["user_id"]; x != nil {
		if y, ok := x.(string); ok {
			target.UserId = y
		}
	}

	if x := source["user_settings"]; x != nil {
		if y, ok := x.(map[string]interface{}); ok {
			target.UserSettings = y
		}
	}

	return nil
}
